name: CI

on: push

jobs:

  windows-x86:
    name: Windows
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,18.0)' # use v143

      - name: Acquire lua and setup directory "deps"
        run: |
          curl -L -o lua-5.4.6.zip https://www.nuget.org/api/v2/package/lua/5.4.6
          7z e lua-5.4.6.zip -o"build-x86-5.4.6/deps" build/native/lib/Win32/v143/Release/lua.lib
          7z e lua-5.4.6.zip -o"build-x86-5.4.6/deps" build/native/lib/Win32/v143/Release/lua_static.lib
          7z e lua-5.4.6.zip -o"build-x86-5.4.6/deps" build/native/bin/Win32/v143/Release/lua.dll
          7z e lua-5.4.6.zip -o"build-x86-5.4.6/deps" build/native/bin/Win32/v143/Release/lua.exe

          7z e lua-5.4.6.zip -o"build-x86-5.4.6/deps/include" build/native/include/*
      
      - name: Build static
        run: |
          pushd build-x86-5.4.6
          meson setup .. -Dlua_version=vendor -Dstatic=true -Dtests=false --buildtype=release
          ninja all
          ninja test
          
          popd


